[build]
  publish = "out"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://api.hisnak.com/v1"
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY = "pk_live_your_stripe_public_key"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://api-staging.hisnak.com/v1"
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY = "pk_test_your_stripe_test_key"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://api-dev.hisnak.com/v1"
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY = "pk_test_your_stripe_test_key"